@baseUrl = http://localhost:8080/v1

POST {{baseUrl}}/create/appointment
Content-Type: application/json

{
    "title": "My graduation",
    "description": "My college education",
    "date": "2024-12-21",
    "interval": 12
}

###
GET {{baseUrl}}/appointments